In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('mit_dataset3.csv')

df.head()

,HR,RR_mean,RR_std,Quality,RMSSD,pNN50,CV,SDSD,RR_Range,Label
0,103.846869,0.746667,0.209419,0.826844,0.256013,44.444444,0.280471,0.244591,0.830556,Suspicious
1,74.633960,0.811389,0.078227,0.927448,0.136827,33.333333,0.096412,0.136827,0.341667,Suspicious
2,74.867580,0.808889,0.078507,0.927208,0.137025,33.333333,0.097055,0.137002,0.341667,Suspicious
3,75.240104,0.805000,0.079260,0.926561,0.136937,33.333333,0.098459,0.136924,0.341667,Suspicious
4,74.786788,0.810000,0.079662,0.926216,0.138725,44.444444,0.098348,0.138626,0.341667,Suspicious


In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105569 entries, 0 to 105568
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   HR        105569 non-null  float64
 1   RR_mean   105569 non-null  float64
 2   RR_std    105569 non-null  float64
 3   Quality   105569 non-null  float64
 4   RMSSD     105569 non-null  float64
 5   pNN50     105569 non-null  float64
 6   CV        105569 non-null  float64
 7   SDSD      105569 non-null  float64
 8   RR_Range  105569 non-null  float64
 9   Label     105569 non-null  str    
dtypes: float64(9), str(1)
memory usage: 8.1 MB


In [4]:
df.isnull().sum()

HR          0
RR_mean     0
RR_std      0
Quality     0
RMSSD       0
pNN50       0
CV          0
SDSD        0
RR_Range    0
Label       0
dtype: int64

In [5]:
df['Label'].value_counts()

Label
Normal        67681
Critical      31221
Suspicious     6667
Name: count, dtype: int64

In [6]:
# Independent Feature
X = df.drop('Label', axis=1)

# Dependent Feature
y = df['Label']

In [7]:
X.head()

,HR,RR_mean,RR_std,Quality,RMSSD,pNN50,CV,SDSD,RR_Range
0,103.846869,0.746667,0.209419,0.826844,0.256013,44.444444,0.280471,0.244591,0.830556
1,74.633960,0.811389,0.078227,0.927448,0.136827,33.333333,0.096412,0.136827,0.341667
2,74.867580,0.808889,0.078507,0.927208,0.137025,33.333333,0.097055,0.137002,0.341667
3,75.240104,0.805000,0.079260,0.926561,0.136937,33.333333,0.098459,0.136924,0.341667
4,74.786788,0.810000,0.079662,0.926216,0.138725,44.444444,0.098348,0.138626,0.341667


In [8]:
y.head()

0    Suspicious
1    Suspicious
2    Suspicious
3    Suspicious
4    Suspicious
Name: Label, dtype: str

# Train Test Split

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

# Random Forest Classifier

In [10]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1, max_depth=20)

In [11]:
rf.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",20
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric(y

In [12]:
y_test_pred = rf.predict(X_test)

# Performance Metrics for Random Forest

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score

print("Performance Metrics using Random Forest Classifier \n")

print("Accuracy Score: ")
print(accuracy_score(y_test, y_test_pred), "\n")

print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_test_pred), "\n")

print("Classification Report: ")
print(classification_report(y_test, y_test_pred))

Performance Metrics using Random Forest Classifier 

Accuracy Score: 
0.9129013924410344 

Confusion Matrix: 
[[ 5540   664    40]
 [  696 12801    39]
 [  235   165   934]] 

Classification Report: 
              precision    recall  f1-score   support

    Critical       0.86      0.89      0.87      6244
      Normal       0.94      0.95      0.94     13536
  Suspicious       0.92      0.70      0.80      1334

    accuracy                           0.91     21114
   macro avg       0.91      0.84      0.87     21114
weighted avg       0.91      0.91      0.91     21114



In [14]:
rf_model = RandomForestClassifier(
    n_estimators=400,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

In [15]:
rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",400
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

In [16]:
y_test_pred_2 = rf_model.predict(X_test)

In [17]:
print("Accuracy Score: ")
print(accuracy_score(y_test, y_test_pred_2), "\n")

print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_test_pred_2), "\n")

print("Classification Report: ")
print(classification_report(y_test, y_test_pred_2))

Accuracy Score: 
0.915790470777683 

Confusion Matrix: 
[[ 5547   654    43]
 [  658 12843    35]
 [  222   166   946]] 

Classification Report: 
              precision    recall  f1-score   support

    Critical       0.86      0.89      0.88      6244
      Normal       0.94      0.95      0.94     13536
  Suspicious       0.92      0.71      0.80      1334

    accuracy                           0.92     21114
   macro avg       0.91      0.85      0.87     21114
weighted avg       0.92      0.92      0.92     21114



# Encoding Labels

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_test_enc = le.transform(y_test)


# Compute Class Weights

In [19]:
from sklearn.utils.class_weight import compute_class_weight

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))
print(class_weights)

{'Critical': np.float64(1.1271036019804888), 'Normal': np.float64(0.5199310493428141), 'Suspicious': np.float64(5.278767422963935)}


In [20]:
sample_weights = np.array([class_weights[i] for i in y_train])

# XGBoost Classifier

In [23]:
from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='mlogloss'
)

xgb.fit(
    X_train,
    y_train_enc,
    sample_weight = sample_weights
)

,"objective objective: typing.Union[str, xgboost.sklearn._SklObjWProto, typing.Callable[[typing.Any, typing.Any], typing.Tuple[numpy.ndarray, numpy.ndarray]], NoneType]Specify the learning task and the corresponding learning objective or a customobjective function to be used.For custom objective, see :doc:`/tutorials/custom_metric_obj` and:ref:`custom-obj-metric` for more information, along with the end note forfunction signatures.",'multi:softprob'
,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API `... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes fr

In [24]:
y_pred_xgb = xgb.predict(X_test)

# Performance Metrics using XGBoost Classifier

In [25]:
print("Performance Metrics using XGBoost Classifier \n")

print("Accuracy Score: ")
print(accuracy_score(y_test_enc, y_pred_xgb), "\n")

print("Confusion Matrix: ")
print(confusion_matrix(y_test_enc, y_pred_xgb), "\n")

print("Classification Report: ")
print(classification_report(y_test_enc, y_pred_xgb))

Performance Metrics using XGBoost Classifier 

Accuracy Score: 
0.8701809226105901 

Confusion Matrix: 
[[ 5497   302   445]
 [ 1351 11768   417]
 [  150    76  1108]] 

Classification Report: 
              precision    recall  f1-score   support

           0       0.79      0.88      0.83      6244
           1       0.97      0.87      0.92     13536
           2       0.56      0.83      0.67      1334

    accuracy                           0.87     21114
   macro avg       0.77      0.86      0.81     21114
weighted avg       0.89      0.87      0.88     21114



# Gradient Boosting

In [26]:
from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

gb.fit(X_train, y_train, sample_weight=sample_weights)


,"loss loss: {'log_loss', 'exponential'}, default='log_loss'The loss function to be optimized. 'log_loss' refers to binomial andmultinomial deviance, the same as used in logistic regression.It is a good choice for classification with probabilistic outputs.For loss 'exponential', gradient boosting recovers the AdaBoost algorithm.",'log_loss'
,"learning_rate learning_rate: float, default=0.1Learning rate shrinks the contribution of each tree by `learning_rate`.There is a trade-off between learning_rate and n_estimators.Values must be in the range `[0.0, inf)`.For an example of the effects of this parameter and its interaction with``subsample``, see:ref:`sphx_glr_auto_examples_ensemble_plot_gradient_boosting_regularization.py`.",0.05
,"n_estimators n_estimators: int, default=100The number of boosting stages to perform. Gradient boostingis fairly robust to over-fitting so a large number usuallyresults in better performance.Values must be in the range `[1, inf)`.",300
,"subsample subsample: float, default=1.0The fraction of samples to be used for fitting the individual baselearners. If smaller than 1.0 this results in Stochastic GradientBoosting. `subsample` interacts with the parameter `n_estimators`.Choosing `subsample < 1.0` leads to a reduction of varianceand an increase in bias.Values must be in the range `(0.0, 1.0]`.",1.0
,"criterion criterion: {'friedman_mse', 'squared_error'}, default='friedman_mse'The function to measure the quality of a split. Supported criteria are'friedman_mse' for the mean squared error with improvement score byFriedman, 'squared_error' for mean squared error. The default value of'friedman_mse' is generally the best as it can provide a betterapproximation in some cases... versionadded:: 0.18",'friedman_mse'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, values must be in the range `[2, inf)`.- If float, values must be in the range `(0.0, 1.0]` and `min_samples_split` will be `ceil(min_samples_split * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, values must be in the range `[1, inf)`.- If float, values must be in the range `(0.0, 1.0)` and `min_samples_leaf` will be `ceil(min_samples_leaf * n_samples)`... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.Values must be in the range `[0.0, 0.5]`.",0.0
,"max_depth max_depth: int or None, default=3Maximum depth of the individual regression estimators. The maximumdepth limits the number of nodes in the tree. Tune this parameterfor best performance; the best value depends on the interactionof the input variables. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.If int, values must be in the range `[1, inf)`.",3
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.Values must be in the range `[0.0, inf)`.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``,

In [27]:
y_pred_gb = gb.predict(X_test)

# Performance Metrics using Gradient Boosting

In [28]:
print("Performance Metrics using Gradient Boosting \n")

print("Accuracy Score: ")
print(accuracy_score(y_test, y_pred_gb), "\n")

print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred_gb), "\n")

print("Classification Report: ")
print(classification_report(y_test, y_pred_gb))

Performance Metrics using Gradient Boosting 

Accuracy Score: 
0.8257554229421237 

Confusion Matrix: 
[[ 5206   290   748]
 [ 1588 11216   732]
 [  238    83  1013]] 

Classification Report: 
              precision    recall  f1-score   support

    Critical       0.74      0.83      0.78      6244
      Normal       0.97      0.83      0.89     13536
  Suspicious       0.41      0.76      0.53      1334

    accuracy                           0.83     21114
   macro avg       0.70      0.81      0.74     21114
weighted avg       0.87      0.83      0.84     21114



In [30]:
rf.feature_importances_

array([0.1077281 , 0.09533754, 0.08138973, 0.07871355, 0.12664424,
       0.04838741, 0.16257831, 0.18138146, 0.11783966])

The order is

[HR,
 RR_mean,
 RR_std,
 Quality,
 RMSSD,
 pNN50,
 CV,
 SDSD,
 RR_range]

# Save the model in a .pkl file

In [37]:
import pickle

with open("cardioguard_rf_model.pkl", "wb") as file:
    pickle.dump(rf_model, file)

# Test Loading the model

In [38]:
with open("cardioguard_rf_model.pkl","rb") as file:
    loaded_model = pickle.load(file)

loaded_model.predict(X_test[:5])

array(['Critical', 'Critical', 'Normal', 'Normal', 'Critical'],
      dtype=object)

In [39]:
sample_input = np.array([
    103.846, 0.811, 0.078, 0.926, 0.138, 44.44, 0.097, 0.126, 0.222
]).reshape(1, -1)

prediction = loaded_model.predict(sample_input)
print("Prediction: ")
print(prediction)

print("\nProbability values of each class: ")
print("[[Critical   Normal  Suspicious]]")
print(loaded_model.predict_proba(sample_input))

Prediction: 
['Critical']

Probability values of each class: 
[[Critical   Normal  Suspicious]]
[[0.6025 0.1875 0.21  ]]
